steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/model-governance-kpmg-ggn/bank-campaign-model', '.']

- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/model-governance-kpmg-ggn/bank-campaign-model']

- name: 'gcr.io/model-governance-kpmg-ggn/bank-campaign-model'
  entrypoint: 'bash'
  args:
   - '-c'
   - |
      python -m pytest

- name: 'gcr.io/cloud-builders/git'
  args: ['clone', 'https://github.com/hemantkkb/model-training-repo.git']

- name: 'gcr.io/cloud-builders/gsutil'
  args: ['cp', 'model-training-repo/bank_campaign_model_training.py', 'gs://bucket-model-governance/dags']

images:
- 'gcr.io/model-governance-kpmg-ggn/bank-campaign-model'

options:
  logging: CLOUD_LOGGING_ONLY